### ISSUE TITLE
Deployment checklist for 3.0

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/broadcast-portal#70]
- [x] Add favicon (see #69)
- [x] Set up mailing list ID and API keys
- [x] Set up SMTP for transactional email (Mandrill?)
- [x] Set up report@ email
- [x] Set up 'filecaster-staging' subdomain
- [ ] Complete #71 
- [ ] Stage
- [ ] Recheck everything once hooked up
- [ ] Set up 'filecaster' subdomain
- [ ] Release
- [ ] Deploy final version
- [ ] Do a quick test on the final version
